<?php require_once "./templates/header.phtml";?>

<div class="card">
  <h5 class="card-header">About</h5>
  <div class="card-body">
    <h5 class="card-title">Motivo por el cual fue creado el sitio</h5>
    <p class="card-text">Esta página fue creada con el fin de brindarle al usuario un sitio en el que pueda recorrer y buscar una amplia gama de calzados de diferentes tipos. Se puede realizar la búsqueda por marcas y, acceder y comprar el producto que desee. Con esto buscamos ayudar a la fácil elección de calzado para las personas que ingresan al sitio. Estos modelos se amoldan a los gustos particulares de cada persona, brindando tanto modelos deportivos como urbanos.</p>
    <a href="<?=BASE_URL?>listarProd" class="btn btn-primary">Página principal</a>
  </div>
</div>

<?php require_once "./templates/footer.phtml";?>