<?php
require_once "./templates/header.phtml";


?>
<h2>Motivo por el cual fue creada la pagina</h2>

<p>Esta página fue creada a fin de poder recorrer la misma para elegir tipos de calzado de diferentes tipos, los cuales se pueden elegir por marcas o por tipos.
   Con esto buscamos ayudar a la fácil elección de calzado para las personas que ingresan a la página.
   Estos modelos se amoldan a los gustos particulares de cada persona, brindando tanto modelos deportivos como urbanos.
     
</p>

<?php require_once "./templates/footer.phtml";
?>