</main>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<!-- fin main container -->

<!-- main footer -->
<footer >
      <div class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
        <span class="text-muted">ShoeSpot - 2023</span>
      </div>
</footer>
  
<script></script>

</body>
</html>
