<?php require './templates/header.phtml';?>

<h2>Modificar Producto</h2>

<form action="<?=BASE_URL?>modificarProd/<?= $product->id ?>" method="POST">
    <div class="mb-3">  
        <label for="nombre" class="form-label">Nombre del producto: </label><input type="text" name="nombre" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?= $product->nombre_producto?>">
    </div>
    <div class="mb-3">
        <label for="color" class="form-label">Color: </label><input type="text" name="color" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?= $product->color?>">
    </div>
    <div class="mb-3">
        <label for="tipo" class="form-label">Tipo: </label><input type="text" name="tipo" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?= $product->tipo?>">
    </div>
    <div class="mb-3">
        <label for="talle" class="form-label">Talle: </label><input type="text" name="talle" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?= $product->talle?>">
    </div>
    <div class="mb-3">
        <label for="precio" class="form-label">Precio: </label><input type="text" name="precio" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?= $product->precio?>">
    </div>
    <div class="mb-3">
        <label for="imagen" class="form-label">URL Imagen: </label><input type="text" name="imagen" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?= $product->url_imagenP?>" maxlength="300">
    </div>
    <div class="mb-3">
        <label for="marca">Marca: </label><input type="text" name="marca" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value="<?= $product->nombre_marca?>">
    </div>
    

    <button type="submit" class="btn btn-primary" >Modificar producto</button>

</form>

<?php require './templates/footer.phtml';?>

