<?php require_once "./templates/header.phtml";?>


    <div>
        <form method="POST" action="auth">
            <div>
                <label for="userName" >Nombre de Usuario</label>
                <input name="userName" required type="text">
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" required name="password">
            </div>       
        
            <button type="submit">Log in</button>
        </form>
    </div>

    <?php require_once "./templates/footer.phtml";

?>