
<h2>Agregar Marca</h2>

<form action="agregarMarca" method="POST">
    <label for="nombre">Nombre de la marca: </label><input type="text" name="nombre">
    <label for="anio">Año de creación: </label><input type="text" name="anio">
    <label for="localizacion">Localización: </label><input type="text" name="localizacion">
    
    <button type="submit" class="btn btn-primary">Agregar marca</button>
</form>
