<?php require_once "./templates/header.phtml";?>


    <div>
        <form method="POST" action="auth">
            <div class="mb-3">
                <label for="userName"  class="form-label" >Nombre de Usuario</label>
                <input name="userName" required type="text" class="form-control">
            </div>

            <div class="mb-3">
                <label for="password" class="form-label" >Password</label>
                <input type="password" required name="password" class="form-control">
            </div>       
        
            <button type="submit" class="btn btn-primary">Log in</button>
        </form>
    </div>
<?php

 ?>

    <?php require_once "./templates/footer.phtml";

?>
