<h2>Agregar producto</h2>

<form action="agregarProd" method="POST">
    <label for="nombre">Nombre del producto: </label><input type="text" name="nombre">
    <label for="color">Color: </label><input type="text" name="color">
    <label for="tipo">Tipo: </label><input type="text" name="tipo">
    <label for="talle">Talle: </label><input type="text" name="talle">
    <label for="precio">Precio: </label><input type="text" name="precio">
    <label for="marca">Marca: </label><select name="marca" id="marca"><?php foreach($marcas as $marca):?> <option value="<?=$marca->id_marcas?>"><?=$marca->nombre_marca?></option><?php endforeach ?></select>
    <button type="submit">Agregar producto</button>
</form>