<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Nombre de la Pagina</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav >
            <div >
                <a href="">Ventas de Calsado</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                </button>
                <div >
                    <ul>
                        <li>
                            <a class="nav-link" aria-current="page" href="">Tareas</a>
                        </li>
                        <li>
                            <a class="nav-link" aria-current="page" href="about">About</a>
                        </li>
                       //preguntar si va eso 
                        <?php if (!isset($_SESSION['USER_ID'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="login">Login</a>
                        </li>
                        <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_EMAIL'] ?>)</a>
                        </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
            </nav>
    </header>

    <!-- inicio main container -->
    <main class="container mt-3">
