<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>ShoeSpot</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <h1><a href="<?=BASE_URL?>listarProd">ShoeSpot</a></h1>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        
                        <li class="nav-item">
                            <a  class="nav-link active" aria-current="page"  href="about">About</a>
                        </li>

                        <?php if (!isset($_SESSION['USER_ID'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="login">Login</a>
                        </li>
                        <?php else : ?>
                        <li>
                            <a  class="nav-link active" aria-current="page" href="<?=BASE_URL?>logout">Logout (<?= $_SESSION['USER_NAME'] ?>)</a>
                        </li>
                        <li>
                            <a class="nav-link active" aria-current="page" href="<?=BASE_URL?>listarProdAdmin">Edición de lista de productos y marcas</a>
                        </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- inicio main container -->
    <main class="container mt-3">