<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Nombre de la Pagina</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav >
            <div >
                <h1><a href="<?=BASE_URL?>listarProd">Ventas de Calzado</a></h1>
                <div>
                    <ul>
                        
                        <li>
                            <a href="about">About</a>
                        </li>

                        <?php if (!isset($_SESSION['USER_ID'])) : ?>
                        <li>
                            <a href="login">Login</a>
                        </li>
                        <?php else : ?>
                        <li>
                            <a href="<?=BASE_URL?>logout">Logout (<?= $_SESSION['USER_NAME'] ?>)</a>
                        </li>
                        <li>
                            <a href="<?=BASE_URL?>listarProdAdmin">Edición de lista de productos</a>
                        </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- inicio main container -->
    <main class="container mt-3">