<?php require './templates/header.phtml';?>

<table class="table table-bordered">
    <thead>
        <tr>   
            <th>id_marca</th>
            <th>nombre_marca</th>
            <th>Año de creación</th>
            <th>Localización de fábrica</th>
            <th>URL Imagen</th>
        </tr>
    </thead>

    <tbody>
    <?php foreach($marcas as $marca): ?>
        <tr>
            <td> <?= $marca->id_marcas ?> </td>    
            <td> <?= $marca->nombre_marca ?> </td>
            <td> <?= $marca->fecha_creacion?> </td>
            <td> <?= $marca->loc_fabrica?> </td>
            <td> <?= $marca->url_imagen?> </td>
            <td><a href="<?=BASE_URL?>showFormModifMarca/<?= $marca->id_marcas ?>" type="button">Modificar</a></td>
            <td><a href="<?=BASE_URL?>eliminarMarca/<?= $marca->id_marcas ?>" type="button">Borrar</a></td>
            
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<?php require './templates/formAddMarca.phtml';?>

<button type="submit" class="btn btn-primary btn-lg"><a class="btn btn-primary btn-lg" href="listarProdAdmin">Finalizar cambios</a></button>

<?php require './templates/footer.phtml';?>