<?php require './templates/header.phtml';?>

<h2>Tabla de productos</h2>

<table class="table table-bordered">
    <thead>
        <tr>   
            <th>id</th>
            <th>Nombre del producto</th>
            <th>Color</th>
            <th>Talle</th>
            <th>Tipo</th>
            <th>Precio</th>
            <th>ID_Marca</th>
        </tr>
    </thead>

    <tbody>
    <?php foreach($products as $product){ ?>
        <tr>
            <td> <?= $product->id ?> </td>
            <td> <?= $product->nombre_producto?> </td>
            <td> <?= $product->color?> </td>
            <td> <?= $product->talle?> </td>
            <td> <?= $product->tipo?> </td>
            <td> <?= $product->precio?> </td>
            <td> <?= $product->id_marca_fk?> </td>
            <td><a href="<?=BASE_URL?>showFormModifProd/<?= $product->id ?>" type="button">Modificar</a></td>
            <td><a href="<?=BASE_URL?>eliminarProd/<?= $product->id ?>" type="button">Borrar</a></td>
            
        </tr>
    <?php } ?>
    </tbody>
</table>

<?php require './templates/formAddProd.phtml';?>

<button type="submit"><a class="btn btn-primary" href="listarMarcas">Listar Marcas</a></button>

<?php require './templates/footer.phtml';?>