
<?php require './templates/header.phtml';?>

<h2>Lista de productos: <?= $products[0]->nombre_marca?></h2>
<div>
    <ul class="tarjetasProdMarca">
        <?php foreach($products as $product): ?>
        <li> 
            <div class="card" style="width: 18rem;">
                <img src="<?= $product->url_imagenP?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"><?= $product->nombre_producto?></h5>
                    <p class="card-text">Marca: <?=$marca->nombre_marca?> </p>
                    <a href="<?=BASE_URL?>detalles/<?= $product->id ?>" class="btn btn-primary">Ver detalles</a>
                </div>
            </div> 
        </li>
        <?php endforeach ?>
    </ul>

</div>

<?php require './templates/footer.phtml';?>